version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        GITHUB_PACKAGES_NPM_TOKEN: "${GITHUB_PACKAGES_NPM_TOKEN}"
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      NODE_ENV: docker_compose
    env_file:
      - ./.env
    volumes:
      - ./src:/app/src
  mongo:
    image: mongo
    ports:
      - "27017:27017"
