version: "3.9"
services:
  api:
    build:
      context: .
      args:
        GITHUB_PACKAGES_NPM_TOKEN: "${GITHUB_PACKAGES_NPM_TOKEN}"
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
    env_file:
      - ./.env
  mongodb:
    image: mongo
